#!/bin/bash

mkdir -p tests/.tmp

for I in {0..10}
do
	echo "===== TEST $I DIFF ====="
	/bin/sh kladoi-compiler.sh `printf 'tests/test%02d.kld' $I` > `printf 'tests/.tmp/test%02d.out' $I`
	diff `printf 'tests/ejm-out/test%02d.out' $I` `printf 'tests/.tmp/test%02d.out' $I`
done
